### ISSUE TITLE
Concern about CWI (channel-wise interpolation) in TAS.

### ISSUE THREAD

**Issue by 104440661** [D-X-Y/NAS-Projects#34]
Hi, thanks for your great work.

After reading your paper TAS,  I don't understand the channel-wise interpolation.  Could you explain or give an insight on channel-wise interpolation (i.e.,  making weighted sum on feature maps of different sizes), and the corresponding effects. 

Thanks.

**Comment by D-X-Y** [comment]
Thanks for your interest.
The CWI operation aims to align the shape of different feature maps. For example, to aggregate two feature maps A in R^{H*W*C1} and B^{H*W*C2}, you can not weighted-sum them due to the inconsistent shape. So we use CWI (https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/shape_searchs/SoftSelect.py#L41) to align their shapes.

**Comment by 104440661** [comment]
Thanks.
