### ISSUE TITLE
How to set the $path_to_meta_nas_bench_file in NAS-BENCH-102?

### ISSUE THREAD

**Issue by MiaoZhang0525** [D-X-Y/NAS-Projects#41]
Hi, Xuanyi,

I am very interested in the NAS-Bench-102, but how to set the path to build a API?

Did you release the benchmark files?

Manly thanks.

**Comment by D-X-Y** [comment]
Hi @MiaoZhang0525 
Thanks a lot for your interest.
I just uploaded the benchmark file on Google Drive, please download it from https://github.com/D-X-Y/NAS-Projects/blob/master/NAS-Bench-102.md#nas-bench-102-extending-the-scope-of-reproducible-neural-architecture-search. After that, you can set the path as this file.
Since we need to address the questions of ICLR reviewers, the API might change in the future (I will add more functions and try my best to maintain the current APIs).
