### ISSUE TITLE
Darts models (V1, V2) are the same?

### ISSUE THREAD

**Issue by semin-park** [D-X-Y/NAS-Projects#46]
**Describe the bug**

If you look at the V1 and V2 of your DARTS implementation, it seems like they are exactly the same. Is this intended?

[V1](https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/cell_searchs/search_model_darts_v1.py) and [V2](
https://github.com/D-X-Y/NAS-Projects/blob/master/lib/models/cell_searchs/search_model_darts_v2.py)

**Comment by D-X-Y** [comment]
Yes, their models are the same, the only difference is optimization: one using first-order approximation, and another using the second-order calculation for the architecture encoding. I implement their optimization in other python files instead of the model files:
https://github.com/D-X-Y/NAS-Projects/blob/master/exps/algos/DARTS-V2.py#L46
